server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity-service/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog-service/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**

jwt:
  secret: "secret123secret123secret123secret123"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: identity-service
        url: /identity-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
      - name: catalog-service
        url: /catalog-service/v3/api-docs
      - name: payment-service
        url: /payment-service/v3/api-docs
      - name: inventory-service
        url: /inventory-service/v3/api-docs
  api-docs:
    enabled: true
