server:
  port: 8083

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:h2:mem:catalogdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop   # Tạo bảng từ entity, drop khi stop app
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true  # Đợi JPA tạo bảng xong rồi mới chạy data.sql

  sql:
    init:
      mode: always            # Luôn chạy data.sql khi start app

# Nếu sau này bạn kết nối RabbitMQ để bắn event (ProductPriceChangedEvent)
# thì bật phần này, còn giờ test CRUD thì có thể để yên
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
#
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#    ip-address: 127.0.0.1


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

