server:
  port: 8081

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:h2:mem:identitydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "secret123secret123secret123secret123" # >= 32 ký tự
  expiration: 86400000 # 1 ngày

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#    ip-address: 127.0.0.1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
