server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/mscnptpm/e-commerce-config.git
          default-label: main
          search-paths:
            - configs
